name: Fast Webhook

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    steps:
      - uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://webhook.fdrive.se/hooks/redeploy-webhook
